import { JSDOM, VirtualConsole } from 'jsdom';
import fs from 'node:fs';
const html = fs.readFileSync('/home/user/bulsuosr-src/OSR/osr-website/design-system.html','utf8');
const errs=[]; const vc=new VirtualConsole();
vc.on('jsdomError', e=>errs.push('jsdomError: '+(e.message||e))); vc.on('error',(...a)=>errs.push('err: '+a.join(' '))); vc.on('warn',()=>{});
const dom=new JSDOM(html,{runScripts:'dangerously',pretendToBeVisual:true,url:'https://bulsuosr.netlify.app/design-system.html',virtualConsole:vc});
const d=dom.window.document;
await new Promise(r=>setTimeout(r,600));
const sw = d.getElementById('swatchBrand')?.querySelector('.swatch__meta span')?.textContent;
const cr = d.getElementById('contrastBody')?.textContent.replace(/\s+/g,' ').trim().slice(0,120);
const tr = d.getElementById('typeRows')?.textContent.replace(/\s+/g,' ').trim().slice(0,100);
const rc = d.getElementById('contrastBody')?.children.length;
console.log('swatch sample:', JSON.stringify(sw));
console.log('contrast rows:', rc, '| first:', cr);
console.log('type rows:', d.getElementById('typeRows')?.children.length, '| first:', tr);
console.log('space rows:', d.getElementById('spaceRows')?.children.length);
console.log('radius rows:', d.getElementById('radiusRows')?.children.length);
console.log('motion rows:', d.getElementById('motionBody')?.children.length);
console.log('errors:', errs.length); errs.slice(0,6).forEach(e=>console.log('  ',e.slice(0,160)));
try{dom.window.close()}catch{}; process.exit(0);
